# Generated by Django 4.2.7 on 2023-11-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartaporte',
            fields=[
                ('numero', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartaportes_destinatario', to='catalog.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('chasis', models.CharField(max_length=50)),
                ('fabricacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='conductor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Manifiesto',
            fields=[
                ('numero', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('cartaporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cartaporte')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='cartaporte',
            name='manifiestos',
            field=models.ManyToManyField(related_name='cartaportes', to='catalog.manifiesto'),
        ),
        migrations.AddField(
            model_name='cartaporte',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartaportes_remitente', to='catalog.empresa'),
        ),
    ]
