# Generated by Django 4.2.7 on 2023-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_cartaporte_vehiculo_alter_conductor_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaporte',
            name='numero',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartaporte',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='documento',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='nacionalidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipoId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manifiesto',
            name='numero',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manifiesto',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='chasis',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fabricacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='pais',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
