# Generated by Django 4.2.7 on 2023-11-20 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_cartaporte_fecha_emision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaporte',
            name='manifiestos',
        ),
        migrations.AlterField(
            model_name='cartaporte',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartaportes_destinatario', to='catalog.empresa'),
        ),
        migrations.AlterField(
            model_name='cartaporte',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartaportes_remitente', to='catalog.empresa'),
        ),
        migrations.AlterField(
            model_name='manifiesto',
            name='cartaporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.cartaporte'),
        ),
        migrations.AlterField(
            model_name='manifiesto',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.conductor'),
        ),
        migrations.AlterField(
            model_name='manifiesto',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.vehiculo'),
        ),
    ]
